##### Part 1 Data Extraction

In [1]:
import yfinance as yf
import numpy as np
import pandas as pd

from tqdm import tqdm
from datetime import datetime

In [2]:
tickers = ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META"]

In [3]:
yf.Ticker('APPL').info

{'quoteType': 'MUTUALFUND',
 'symbol': 'APPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Fund',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'NONE',
 'corporateActions': [],
 'regularMarketTime': 1561759658,
 'exchange': 'YHD',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'CLOSED',
 'hasPrePostMarketData': False,
 'priceHint': 2,
 'fullExchangeName': 'YHD',
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'tradeable': False,
 'cryptoTradeable': False,
 'trailingPegRatio': None}

In [4]:
def get_company_info(ticker):
    stock = yf.Ticker(ticker)
    info = stock.info
    return {
        'ticker': ticker,
        'company_name': info.get('longName'),
        'sector': info.get('sector'),
        'industry': info.get('industry'),
        'country': info.get('country'),
        'market_cap': info.get('marketCap'),
        'website': info.get('website')
    }

get_company_info('NVDA')

{'ticker': 'NVDA',
 'company_name': 'NVIDIA Corporation',
 'sector': 'Technology',
 'industry': 'Semiconductors',
 'country': 'United States',
 'market_cap': 4967727366144,
 'website': 'https://www.nvidia.com'}

In [5]:
company_records = []

for ticker in tickers:
    try:
        company_records.append(get_company_info(ticker))
    except Exception as e:
        print(ticker, e)

companies_df = pd.DataFrame(company_records)
companies_df.head()

,ticker,company_name,sector,industry,country,market_cap,website
0,AAPL,Apple Inc.,Technology,Consumer Electronics,United States,4514011676672,https://www.apple.com
1,MSFT,Microsoft Corporation,Technology,Software - Infrastructure,United States,3095206035456,https://www.microsoft.com
2,NVDA,NVIDIA Corporation,Technology,Semiconductors,United States,4967727366144,https://www.nvidia.com
3,AMZN,"Amazon.com, Inc.",Consumer Cyclical,Internet Retail,United States,2646571745280,https://www.amazon.com
4,GOOGL,Alphabet Inc.,Communication Services,Internet Content & Information,United States,4494199357440,https://abc.xyz

In [6]:
companies_df.to_parquet("companies.parque", index = False)

In [7]:
def get_price_history(ticker, period = '5y'):
    stock = yf.Ticker(ticker)
    df = stock.history(period = period)
    df.reset_index(inplace = True)
    df['ticker'] = ticker
    return df

nvda_prices = get_price_history('NVDA')
nvda_prices

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker
0,2021-06-07 00:00:00-04:00,17.506672,17.747034,17.129563,17.554245,575756000,0.000,0.0,NVDA
1,2021-06-08 00:00:00-04:00,17.462833,17.556736,17.187597,17.392841,323848000,0.000,0.0,NVDA
2,2021-06-09 00:00:00-04:00,17.455376,17.514422,17.196272,17.298418,381656000,0.004,0.0,NVDA
3,2021-06-10 00:00:00-04:00,17.290200,17.431711,17.116800,17.364941,287772000,0.000,0.0,NVDA
4,2021-06-11 00:00:00-04:00,17.419246,17.877413,17.383620,17.763805,416308000,0.000,0.0,NVDA
...,...,...,...,...,...,...,...,...,...
1251,2026-06-01 00:00:00-04:00,215.478858,224.608217,215.448894,224.098816,212850700,0.000,0.0,NVDA
1252,2026-06-02 00:00:00-04:00,226.915518,232.009586,221.092318,222.560608,193362900,0.000,0.0,NVDA
1253,2026-06-03 00:00:00-04:00,221.461887,222.560613,214.260274,214.500000,160907000,0.000,0.0,NVDA
1254,2026-06-04 00:00:00-04:00,213.910004,221.600006,210.970001,218.660004,169022200,0.250,0.0,NVDA
1255,2026-06-05 00:00:00-04:00,214.529999,214.869995,204.330002,205.100006,218529000,0.000,0.0,NVDA

In [8]:
price_frames = []
for ticker in tqdm(tickers):
    try:
        df = get_price_history(ticker)
        price_frames.append(df)
    except Exception as e:
        print(ticker, e)

prices_df = pd.concat(price_frames)
print(prices_df.shape)

100%|██████████| 6/6 [00:00<00:00,  6.54it/s]

(7536, 9)

In [9]:

prices_df.to_parquet("prices.parquet", index = False)

In [10]:
def get_income_statement(ticker):
    stock = yf.Ticker(ticker)
    income = stock.financials.T
    income['ticker'] = ticker
    return income

def get_balance_sheet(ticker):
    stock = yf.Ticker(ticker)
    balance_sheet = stock.balance_sheet.T
    balance_sheet['ticker'] = ticker
    return balance_sheet

def get_cashflow(ticker):
    stock = yf.Ticker(ticker)
    cashflow = stock.cashflow.T
    cashflow['ticker'] = ticker
    return cashflow

In [11]:
income_frames = []
balance_frames = []
cashflow_frames = []

for ticker in tqdm(tickers):
    try:
        income_frames.append(get_income_statement(ticker))
        balance_frames.append(get_balance_sheet(ticker))
        cashflow_frames.append(get_cashflow(ticker))
    except Exception as e:
        print(ticker, e)


income_df = pd.concat(income_frames)
balance_df = pd.concat(balance_frames)
cashflow_df = pd.concat(cashflow_frames)

income_df.to_parquet("income.parquet", index=False)
balance_df.to_parquet("balance.parquet", index=False)
cashflow_df.to_parquet("cashflow.parquet", index=False)

100%|██████████| 6/6 [00:04<00:00,  1.30it/s]

In [19]:
income_df.isnull().mean().sort_values()

ticker                                                        0.000000
Tax Effect Of Unusual Items                                   0.111111
Net Income Common Stockholders                                0.111111
Net Income                                                    0.111111
Net Income Including Noncontrolling Interests                 0.111111
Net Income Continuous Operations                              0.111111
Tax Provision                                                 0.111111
Pretax Income                                                 0.111111
Other Non Operating Income Expenses                           0.111111
Operating Income                                              0.111111
Operating Expense                                             0.111111
Selling General And Administration                            0.111111
Gross Profit                                                  0.111111
Cost Of Revenue                                               0.111111
Total Revenue                                                 0.111111
Operating Revenue                                             0.111111
Diluted NI Availto Com Stockholders                           0.111111
Basic EPS                                                     0.111111
Other Income Expense                                          0.111111
Basic Average Shares                                          0.111111
Tax Rate For Calcs                                            0.111111
Normalized EBITDA                                             0.111111
Net Income From Continuing Operation Net Minority Interest    0.111111
Reconciled Depreciation                                       0.111111
Diluted EPS                                                   0.111111
EBITDA                                                        0.111111
EBIT                                                          0.111111
Reconciled Cost Of Revenue                                    0.111111
Normalized Income                                             0.111111
Net Income From Continuing And Discontinued Operation         0.111111
Total Expenses                                                0.111111
Total Operating Income As Reported                            0.111111
Diluted Average Shares                                        0.111111
Net Non Operating Interest Income Expense                     0.148148
Interest Expense Non Operating                                0.148148
Interest Income Non Operating                                 0.148148
Net Interest Income                                           0.148148
Interest Expense                                              0.148148
Interest Income                                               0.148148
Total Unusual Items Excluding Goodwill                        0.259259
Total Unusual Items                                           0.259259
Research And Development                                      0.259259
Gain On Sale Of Security                                      0.407407
Selling And Marketing Expense                                 0.407407
General And Administrative Expense                            0.407407
Other Gand A                                                  0.407407
Special Income Charges                                        0.518519
Write Off                                                     0.703704
Earnings From Equity Interest                                 0.851852
Restructuring And Mergern Acquisition                         0.851852
Earnings From Equity Interest Net Of Tax                      0.851852
Other Operating Expenses                                      0.851852
Total Other Finance Cost                                      0.851852
dtype: float64

In [20]:
prices_df.duplicated().sum()

np.int64(0)

In [21]:
prices_df["ticker"].nunique()

6

##### Part 2: News Pipeline


The logic is based on a 4-layer pipeline to process the news and output a formatted message.

Raw News -> Sentiment Layer -> Event Layer -> Risk Layer -> Entity Layer -> Feature Store

In [12]:
from transformers import pipeline

/Users/thomasxiang/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [22]:
ticker = yf.Ticker('NVDA')
ticker.news

[{'id': 'dc6d5fc5-bb0c-4fdc-99f5-309ec954b1b5',
  'content': {'id': 'dc6d5fc5-bb0c-4fdc-99f5-309ec954b1b5',
   'contentType': 'STORY',
   'title': 'AI stock mania is taking over the markets in 2026',
   'description': '',
   'summary': 'It was a mind-blowing week for the AI trade, with only one reasonable conclusion.',
   'pubDate': '2026-06-07T12:30:00Z',
   'displayTime': '2026-06-07T12:30:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/iu8qDSZOEooI60uI6uHNag--~B/aD0zOTk5O3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-06/7806654d-63ff-4cfb-8f0a-2fe1ac08c92c',
    'originalWidth': 6000,
    'originalHeight': 3999,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/iu8qDSZOEooI60uI6uHNag--~B/aD0zOTk5O3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-06/7806654d-63ff-4cfb-8f0a-2fe1ac08c92c',
      'width': 6000,
      'height': 3999,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/x7P2LwTHWU3LkqcN8g2v1w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-06/7806654d-63ff-4cfb-8f0a-2fe1ac08c92c',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/article/ai-stock-mania-is-taking-over-the-markets-in-2026-123000964.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/article/ai-stock-mania-is-taking-over-the-markets-in-2026-123000964.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '6edb6a9d-34b5-4f61-bd55-b598227d4838',
  'content': {'id': '6edb6a9d-34b5-4f61-bd55-b598227d4838',
   'contentType': 'STORY',
   'title': "Wall Street's hottest trade is cracking in a trillion-dollar wipeout",
   'description': '',
   'summary': 'Chip stocks are turning a rough session on Friday into a rout, erasing more than $1 trillion in market value.',
   'pubDate': '2026-06-05T18:45:40Z',
   'displayTime': '2026-06-06T23:33:43Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/uJPmbNJ_WKHRVptN08pdiQ--~B/aD0zNzg0O3c9NTY3NTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-06/5d3f9f72-93ea-4180-b2a9-73bfa69fa0f8',
    'originalWidth': 5675,
    'originalHeight': 3784,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/uJPmbNJ_WKHRVptN08pdiQ--~B/aD0zNzg0O3c9NTY3NTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-06/5d3f9f72-93ea-4180-b2a9-73bfa69fa0f8',
      'width': 5675,
      'height': 3784,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/aZSGYGjJj18pSesaDCWJPg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-06/5d3f9f72-93ea-4180-b2a9-73bfa69fa0f8',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/article/wall-streets-hottest-trade-is-cracking-in-a-trillion-dollar-wipeout-184540683.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/article/wall-streets-hottest-trade-is-cracking-in-a-trillion-dollar-wipeout-184540683.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'd4ff6318-c43d-3ffc-a798-4dd453eae301',
  'content': {'id': 'd4ff6318-c43d-3ffc-a798-4dd453eae301',
   'contentType': 'STORY',
   'title': "Micron's Stock Is Up Over 270% This Year. Here's How It Can Still Double in 2026.",
   'description': '',
   'summary': 'Micron has risen to over a $1 trillion valuation.',
   'pubDate': '2026-06-07T20:31:00Z',
   'displayTime': '2026-06-07T20:31:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/2e69bcdecf78ca2f34490a47d88169b1',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'Stock trader celebrating while looking at screens.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/M3wSqHaUxokaoG9IODJJ2A--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/2e69bcdecf78ca2f34490a47d88169b1',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/FL67UPT6dwqirAsuMob.uA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/2e69bcdecf78ca2f34490a47d88169b1',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/microns-stock-is-up-over-270-this-year/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/microns-stock-over-270-heres-203100938.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '5f9b4a61-95b5-3627-afc1-a3406c5abf84',
  'content': {'id': '5f9b4a61-95b5-3627-afc1-a3406c5abf84',
   'contentType': 'STORY',
   'title': 'Which Big 3 Cloud Computing Stock Is the Best Buy Now?',
   'description': '',
   'summary': 'Cloud computing will benefit from the AI build-out over the long term.',
   'pubDate': '2026-06-07T20:29:00Z',
   'displayTime': '2026-06-07T20:29:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/a5eec221298cabb675d654917c081aac',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Engineer standing in a data center.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gqOpzy1MiTSNu.y8QGFEVA--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/a5eec221298cabb675d654917c081aac',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/6y_gKr4fN11oUBNkfyXcNg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/a5eec221298cabb675d654917c081aac',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/which-big-3-cloud-computing-stock-is-the-best-buy/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/big-3-cloud-computing-stock-202900661.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '77a7e2af-085e-340f-afd8-354145b6d0aa',
  'content': {'id': '77a7e2af-085e-340f-afd8-354145b6d0aa',
   'contentType': 'STORY',
   'title': 'TSMC Nvidia AI Partnership Puts Factory Efficiency And Valuation In Focus',
   'description': '',
   'summary': "TSMC (NYSE:TSM) and Nvidia announced a wide-ranging partnership to apply AI and accelerated computing across TSMC's semiconductor manufacturing operations. The agreement covers areas such as lithography, defect detection, and factory and production optimization within TSMC's fabs. The partnership extends the existing customer supplier relationship into a broader collaboration focused on AI driven chipmaking processes. For you as an investor, this matters because TSMC is a key contract chip...",
   'pubDate': '2026-06-07T20:07:26Z',
   'displayTime': '2026-06-07T20:07:26Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/simply_wall_st__316/ce85212c51bd88fd1fdcd0febb642a4a',
    'originalWidth': 1194,
    'originalHeight': 432,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/5Tyy8Oun7d69.ebTzNgpXA--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/ce85212c51bd88fd1fdcd0febb642a4a',
      'width': 1194,
      'height': 432,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/sdqM2NN9Xy0ai0FXQvYklw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/simply_wall_st__316/ce85212c51bd88fd1fdcd0febb642a4a',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Simply Wall St.',
    'url': 'https://simplywall.st/',
    'sourceId': 'simply_wall_st__316'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/tsmc-nvidia-ai-partnership-puts-200726215.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/tsmc-nvidia-ai-partnership-puts-200726215.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '4ce342ae-ca81-3e6e-aa1b-30b0866eb102',
  'content': {'id': '4ce342ae-ca81-3e6e-aa1b-30b0866eb102',
   'contentType': 'STORY',
   'title': 'Did Anthropic and Google Just Give Investors 2.2 Billion Reasons to Buy the SpaceX IPO?',
   'description': '',
   'summary': 'SpaceX recently unveiled a large new compute deal with Google, in addition to a previously announced one with Anthropic.',
   'pubDate': '2026-06-07T19:58:43Z',
   'displayTime': '2026-06-07T19:58:43Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/b850bcc00e69880fb28e6592a2d3e979',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'Rocket launch.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/wRHIzumr807tuG84Nhw8wA--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/b850bcc00e69880fb28e6592a2d3e979',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Bn5Ndh7QZMAyeQckzAUwZg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/b850bcc00e69880fb28e6592a2d3e979',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/did-anthropic-and-google-just-give-investors-22-billion-reasons-to-buy-the-spacex-ipo/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/did-anthropic-google-just-investors-195843785.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'dd71d561-fccb-38b6-84dc-3ed7d4a354bb',
  'content': {'id': 'dd71d561-fccb-38b6-84dc-3ed7d4a354bb',
   'contentType': 'STORY',
   'title': 'Why Microsoft Distancing Itself From OpenAI Is a Good Thing for Investors',
   'description': '',
   'summary': "Microsoft is building its own AI infrastructure in-house, and that's good news for investors.",
   'pubDate': '2026-06-07T19:31:00Z',
   'displayTime': '2026-06-07T19:31:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/868b8fb1b9e5c7234c64024547714a18',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'The Microsoft logo on a blue backdrop.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/w2mrdoOPrUUq5Me_7ocZ5A--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/868b8fb1b9e5c7234c64024547714a18',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/HKt7j8q3x1XYxMoyqnNLjg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/868b8fb1b9e5c7234c64024547714a18',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/why-microsoft-distancing-from-openai-is-good/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/why-microsoft-distancing-itself-openai-193100411.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'c2875737-3f4e-34c2-8deb-856ec395415a',
  'content': {'id': 'c2875737-3f4e-34c2-8deb-856ec395415a',
   'contentType': 'STORY',
   'title': "Time Is Running Out to Lock In This Financial Stock's Sky-High Yield",
   'description': '',
   'summary': "Ares Capital's next dividend payment is approaching.",
   'pubDate': '2026-06-07T19:20:00Z',
   'displayTime': '2026-06-07T19:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/9b75ff20b2354d7af0f0f74eab77cf1d',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'A person looking up at a large percentage sign.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gtBvZnzWqSE0vzc2jWmwOw--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/9b75ff20b2354d7af0f0f74eab77cf1d',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/UNpWIsSwIMxUcjB9okLV1g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/9b75ff20b2354d7af0f0f74eab77cf1d',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/time-is-running-out-to-lock-in-this-financial-stoc/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/time-running-lock-financial-stocks-192000918.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '2604b00f-7c16-35f1-ae87-4c6a04490990',
  'content': {'id': '2604b00f-7c16-35f1-ae87-4c6a04490990',
   'contentType': 'STORY',
   'title': 'NVDL Collapsed 12% in a Single Day as Nvidia Lost $279 Billion, Exposing How Leverage Compounds on Bad Tape',
   'description': '',
   'summary': 'If you owned GraniteShares 2x Long NVDA Daily ETF (NASDAQ:NVDL) into the close on Friday, June 5, 2026, your screen looked broken. The fund opened the session near $109.45 and closed at $95.91, a 12% single-day drop. The underlying, NVIDIA (NASDAQ:NVDA), fell 6.2% from $218.66 to $205.10, shedding ~$279 billion in market value in a ... NVDL Collapsed 12% in a Single Day as Nvidia Lost $279 Billion, Exposing How Leverage Compounds on Bad Tape',
   'pubDate': '2026-06-07T19:15:11Z',
   'displayTime': '2026-06-07T19:15:11Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/0c3d6fa4bd95910d49a32773dc939b88',
    'originalWidth': 2560,
    'originalHeight': 1711,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/bP8HCVXdGKyAgciockbPOg--~B/aD0xNzExO3c9MjU2MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/0c3d6fa4bd95910d49a32773dc939b88',
      'width': 2560,
      'height': 1711,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/JJVUbSl2NjrdIRGB8MI.Gw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/0c3d6fa4bd95910d49a32773dc939b88',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/06/07/nvdl-collapsed-12-in-a-single-day-as-nvidia-lost-279-billion-exposing-how-leverage-compounds-on-bad-tape/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvdl-collapsed-12-single-day-191511769.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '959c53d5-9355-36ca-9b41-4b874848d432',
  'content': {'id': '959c53d5-9355-36ca-9b41-4b874848d432',
   'contentType': 'STORY',
   'title': '1 Costly Mistake Too Many Investors Make With the Vanguard S&P 500 ETF (VOO)',
   'description': '',
   'summary': 'Investors in the S&P 500 might not be getting quite what they think they are.',
   'pubDate': '2026-06-07T19:05:00Z',
   'displayTime': '2026-06-07T19:05:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/03840a7f50fa98a54e7bda82b8a06680',
    'originalWidth': 1400,
    'originalHeight': 753,
    'caption': 'Coins, bars, arrows, and "S&P 500."',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gafg6aVmayK3uDBt._RlYw--~B/aD03NTM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/03840a7f50fa98a54e7bda82b8a06680',
      'width': 1400,
      'height': 753,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/rVwooST1KeIuEogNAPM2Jg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/03840a7f50fa98a54e7bda82b8a06680',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/06/07/mistake-investors-make-vanguard-sp-500-etf-voo/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},

In [28]:
ticker.news[0]['content'].keys()

dict_keys(['id', 'contentType', 'title', 'description', 'summary', 'pubDate', 'displayTime', 'isHosted', 'bypassModal', 'previewUrl', 'thumbnail', 'provider', 'canonicalUrl', 'clickThroughUrl', 'metadata', 'finance', 'storyline'])

In [ ]:
def build_article_text(article):
    return f"""
    Title:
    {article.get('title', '')}

    Description:
    {article.get('description', '')}

    Summary:
    {article.get('summary', '')}

    
    """

In [ ]:
sentiment_model = pipeline(
    "text-classification", 
    model = "ProsusAI/finbert", 
    top_k = None)


text = build_article_text(article=ticker.news[0]['content'])


result = sentiment_model(text[:512])

print(result)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 94449.37it/s]

[[{'label': 'neutral', 'score': 0.8348400592803955}, {'label': 'negative', 'score': 0.09783732146024704}, {'label': 'positive', 'score': 0.06732263416051865}]]

In [50]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification


MODEL_NAME = "ProsusAI/finbert"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME
)

sentiment_model = pipeline(
    task = "text-classification", 
    model = model,
    tokenizer = tokenizer,
    top_k = None)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 61406.88it/s]

In [62]:
tokens = tokenizer.tokenize(build_article_text(article=ticker.news[9]['content']))
print(tokens[:20])
print(len(tokens))

['title', ':', '1', 'costly', 'mistake', 'too', 'many', 'investors', 'make', 'with', 'the', 'vanguard', 's', '&', 'p', '500', 'et', '##f', '(', 'vo']
44

In [49]:
sentiment_model(
    text,
    truncation=True,
    max_length=512
)

[[{'label': 'neutral', 'score': 0.8348400592803955},
  {'label': 'negative', 'score': 0.09783732146024704},
  {'label': 'positive', 'score': 0.06732263416051865}]]

In [55]:
result[0]

[{'label': 'neutral', 'score': 0.8348400592803955},
 {'label': 'negative', 'score': 0.09783732146024704},
 {'label': 'positive', 'score': 0.06732263416051865}]

In [56]:
def get_finbert_sentiment(text: str) -> dict:


    results = sentiment_model(
        text,
        truncation=True,
        max_length=512
    )[0]

    scores = {
        item["label"].lower(): float(item["score"])
        for item in results
    }

    sentiment = max(
        scores,
        key=scores.get
    )

    return {
        "sentiment": sentiment,
        "sentiment_score": scores[sentiment],
        "positive_score": scores.get("positive", 0),
        "negative_score": scores.get("negative", 0),
        "neutral_score": scores.get("neutral", 0)
    }

In [57]:
article_text = build_article_text(
    ticker.news[0]["content"]
)

sentiment = get_finbert_sentiment(
    article_text
)

print(sentiment)

{'sentiment': 'neutral', 'sentiment_score': 0.8348400592803955, 'positive_score': 0.06732263416051865, 'negative_score': 0.09783732146024704, 'neutral_score': 0.8348400592803955}

In [63]:
def chunk_text_by_tokens(
    text: str,
    tokenizer,
    max_tokens: int = 512,
    overlap: int = 50
):

    token_ids = tokenizer.encode(
        text,
        add_special_tokens=False
    )

    chunks = []

    start = 0

    while start < len(token_ids):

        end = start + max_tokens

        chunk_ids = token_ids[start:end]

        chunk_text = tokenizer.decode(
            chunk_ids,
            skip_special_tokens=True
        )

        chunks.append(chunk_text)

        start += max_tokens - overlap

    return chunks

In [64]:
long_article = """
Title: MU, NVDA, ORCL, MRVL: Why Are AI and Chip Stocks Bleeding Red Today?

Description:
Chip and AI stocks are under pressure today due to weak signals from the sector and hotter-than-expected economic data. On top of that, traders are taking profits in some of the market’s biggest winners, adding fuel to the selloff. Micron MU -13.25% ▼ , Nvidia NVDA -6.20% ▼ , Oracle ORCL -9.59% ▼ , and Marvell MRVL -16.74% ▼ have declined 11.5%, 7%, 10%, and 13%, respectively, as investors reassess how fast AI spending can grow and how long high interest rates may stay high.



Claim 55% Off TipRanks

Explore NVDS for 2X short leverage on NVDA


Key reasons behind the market’s sharp decline are:


1. Broadcom’s “Reality Check” on AI Spending: The drop began after Broadcom’s AVGO -7.92% ▼ earnings report on June 3. While the company beat estimates, it did not raise its long‑term AI revenue outlook for Fiscal 2026 and 2027. This hit the semiconductor market hard, as a flat forecast signaled that demand may not be rising as quickly as hoped.


2. Hot Jobs Data Pushes Yields Higher: The strong May jobs report showed hiring was hotter than expected, pushing Treasury yields higher and raising worries about a Fed rate hike. Chip and AI stocks are sensitive to rising rates as their biggest profits are expected far in the future. When yields rise, those future earnings get discounted more, and stock prices fall quickly.


3. Heavy Profit‑Taking After a Massive Rally: Many chip names were already stretched after a long run fueled by AI optimism. With valuations sitting at record highs and technical indicators flashing overbought, traders were ready to take profits at the first sign of weakness.


Which Is a Better Stock, MU, NVDA, ORCL, or MRVL?

Using TipRanks’ Stock Comparison Tool, we compared MU, NVDA, ORCL, and MRVL to see which AI stock Wall Street currently favors. All the stocks have a Strong Buy consensus rating on TipRanks, but analysts see the most upside potential in Nvidia stock. The average price target of $311.41 implies about 51.82% upside from the current level.


Summary: 
Chip and AI stocks are sliding after weak forward guidance from Broadcom.
Hot May jobs data pushed yields higher and revived Fed rate‑hike fears.
MU, NVDA, ORCL, and MRVL dropped 11.5%, 7%, 10%, and 13%, respectively.

"""

In [65]:
chunks = chunk_text_by_tokens(
    long_article,
    tokenizer
)

print(len(chunks))

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (567 > 512). Running this sequence through the model will result in indexing errors

2

In [66]:
def sentiment_from_long_article(
    text: str,
    tokenizer,
    sentiment_model,
    max_tokens: int = 512,
    overlap: int = 50
):

    chunks = chunk_text_by_tokens(
        text=text,
        tokenizer=tokenizer,
        max_tokens=max_tokens,
        overlap=overlap
    )

    chunk_results = []

    for chunk in chunks:

        result = get_finbert_sentiment(chunk)

        chunk_results.append(result)

    positive = sum(
        r["positive_score"]
        for r in chunk_results
    ) / len(chunk_results)

    negative = sum(
        r["negative_score"]
        for r in chunk_results
    ) / len(chunk_results)

    neutral = sum(
        r["neutral_score"]
        for r in chunk_results
    ) / len(chunk_results)

    final_scores = {
        "positive": positive,
        "negative": negative,
        "neutral": neutral
    }

    final_sentiment = max(
        final_scores,
        key=final_scores.get
    )

    return {
        "sentiment": final_sentiment,
        "sentiment_score": final_scores[final_sentiment],
        "positive_score": positive,
        "negative_score": negative,
        "neutral_score": neutral,
        "num_chunks": len(chunk_results),
        "chunk_results": chunk_results
    }

In [67]:
result = sentiment_from_long_article(
    text=long_article,
    tokenizer=tokenizer,
    sentiment_model=sentiment_model
)

print(result)

{'sentiment': 'negative', 'sentiment_score': 0.9478254616260529, 'positive_score': 0.0224152822047472, 'negative_score': 0.9478254616260529, 'neutral_score': 0.02975929155945778, 'num_chunks': 2, 'chunk_results': [{'sentiment': 'negative', 'sentiment_score': 0.9223329424858093, 'positive_score': 0.03486869856715202, 'negative_score': 0.9223329424858093, 'neutral_score': 0.04279840365052223}, {'sentiment': 'negative', 'sentiment_score': 0.9733179807662964, 'positive_score': 0.009961865842342377, 'negative_score': 0.9733179807662964, 'neutral_score': 0.016720179468393326}]}

Imrpovement:

#TODO:

Instead of using simple average, the new sentiment score can be reweighted by different componments of the news.

For example:
Headline Weight - 40%, Description Weight - 30%, Summary Weight - 10%, Body Weight - 10%

These weights would be a part of tuning process.

##### Event Layer && Risk Layer && Entity Layer

In [71]:
DEEPSEEK_API_KEY = "sk-78de867c66fc4ef3b6b001b6298dcec2"

In [ ]:
from openai import OpenAI

llm_client = OpenAI(
    api_key=DEEPSEEK_API_KEY,
    base_url="https://api.deepseek.com"
)

In [96]:
EVENT_KEYWORDS = {
    "earnings_beat": [
        "beat estimates",
        "beats estimates",
        "beats expectations",
        "strong earnings"
    ],

    "earnings_miss": [
        "missed estimates",
        "missed expectations"
    ],

    "guidance_raise": [
        "raised guidance",
        "raises guidance",
        "increased outlook"
    ],

    "guidance_cut": [
        "cut guidance",
        "lowered outlook"
    ],

    "acquisition": [
        "acquired",
        "acquires",
        "acquisition"
    ],

    "partnership": [
        "partnership",
        "partnered",
        "collaboration"
    ],

    "lawsuit": [
        "lawsuit",
        "sued",
        "litigation"
    ],

    "stock_buyback": [
        "buyback",
        "share repurchase"
    ]
}

RISK_KEYWORDS = {
    "competition": [
        "competition",
        "competitive pressure",
        "rival"
    ],

    "regulatory": [
        "regulatory",
        "investigation",
        "sec"
    ],

    "litigation": [
        "lawsuit",
        "legal action",
        "litigation"
    ],

    "valuation": [
        "overvalued",
        "valuation concern"
    ],

    "supply_chain": [
        "supply chain",
        "shortage"
    ],

    "cybersecurity": [
        "cyber attack",
        "security breach"
    ]
}

In [97]:
def rule_based_events(text):

    text = text.lower()

    events = []

    for event, keywords in EVENT_KEYWORDS.items():

        if any(
            keyword in text
            for keyword in keywords
        ):
            events.append(event)

    return list(set(events))


def rule_based_risks(text):

    text = text.lower()

    risks = []

    for risk, keywords in RISK_KEYWORDS.items():

        if any(
            keyword in text
            for keyword in keywords
        ):
            risks.append(risk)

    return list(set(risks))

In [98]:
from pydantic import BaseModel
from typing import List
import json
import re

def extract_json(text):

    match = re.search(
        r"\{.*\}",
        text,
        re.DOTALL
    )

    if not match:
        return {}

    try:
        return json.loads(
            match.group()
        )
    except:
        return {}

In [99]:
def llm_extract_news(
    article_text,
    client
):

    prompt = f"""
Analyze this financial article.

Return ONLY JSON.

{{
  "events": [],
  "risks": [],
  "entities": []
}}

Article:

{article_text}
"""

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0
    )

    return extract_json(
        response.choices[0].message.content
    )

In [100]:
def extract_news_intelligence(
    article_text,
    client
):

    sentiment = get_finbert_sentiment(
        article_text
    )

    llm_output = llm_extract_news(
        article_text,
        client
    )

    llm_events = llm_output.get(
        "events",
        []
    )

    llm_risks = llm_output.get(
        "risks",
        []
    )

    llm_entities = llm_output.get(
        "entities",
        []
    )

    rule_events = rule_based_events(
        article_text
    )

    rule_risks = rule_based_risks(
        article_text
    )

    final_events = sorted(
        list(
            set(
                llm_events +
                rule_events
            )
        )
    )

    final_risks = sorted(
        list(
            set(
                llm_risks +
                rule_risks
            )
        )
    )

    return {
        **sentiment,

        "events": final_events,

        "risks": final_risks,

        "entities": llm_entities
    }

In [101]:
article_text = build_article_text(
    ticker.news[0]["content"]
)

result = extract_news_intelligence(
    article_text,
    llm_client
)

print(json.dumps(
    result,
    indent=2
))

{
  "sentiment": "neutral",
  "sentiment_score": 0.8348400592803955,
  "positive_score": 0.06732263416051865,
  "negative_score": 0.09783732146024704,
  "neutral_score": 0.8348400592803955,
  "events": [
    "AI stock mania taking over markets in 2026"
  ],
  "risks": [
    "Potential market overvaluation or bubble in AI stocks"
  ],
  "entities": [
    "AI trade"
  ]
}

The result shows 

```
  {
    "sentiment": "neutral",
    "sentiment_score": 0.8348400592803955,
    "positive_score": 0.06732263416051865,
    "negative_score": 0.09783732146024704,
    "neutral_score": 0.8348400592803955,
    "events": [
      "AI stock mania taking over markets in 2026"
    ],
    "risks": [
      "Potential market overvaluation or bubble in AI stocks"
    ],
    "entities": [
      "AI trade"
    ]
  }
  ```

It shows bad news feed and AI hullucination can lead to poor results. It can be also led by other plausible cause.

In [102]:
# Add a validation layer

def validate_output(result):
    
    # remove hallucinated long phrases
    result["events"] = [
        e for e in result["events"]
        if len(e.split()) <= 5
    ]
    
    result["risks"] = [
        r for r in result["risks"]
        if len(r.split()) <= 6
    ]
    
    return result

In [ ]:
from newsapi import NewsApiClient

# Init
newsapi = NewsApiClient(api_key='b08a728c809d44c5acabf818940a0f84')

/Users/thomasxiang/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm